version: "3.9"

services:
  nginx:
    image: nginx:alpine
    container_name: global-nginx
    ports:
      - "80:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d:/etc/nginx/conf.d
    restart: unless-stopped
    networks:
      - global-nginx_default
      - mom_bitmeetings-network
